#ifndef ECGRAPHICINTERFACE_GLOBAL_H
#define ECGRAPHICINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ECGRAPHICINTERFACE_LIBRARY)
#  define ECGRAPHICINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ECGRAPHICINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ECGRAPHICINTERFACE_GLOBAL_H
