#ifndef SHARE_ANN_BASE_LIB_H
#define SHARE_ANN_BASE_LIB_H

#ifdef EXPORT_ANN_BASE_LIB
#define ANN_BASE_LIB_IMPORT_EXPORT Q_DECL_EXPORT
#else
#define ANN_BASE_LIB_IMPORT_EXPORT Q_DECL_IMPORT
#endif


#endif // SHARE_ANN_GUI_LIB_H
