#ifndef SHARE_CV_GUI_LIB_H
#define SHARE_CV_GUI_LIB_H

#ifdef EXPORT_CV_GUI_LIB
#define CV_GUI_LIB_IMPORT_EXPORT Q_DECL_EXPORT
#else
#define CV_GUI_LIB_IMPORT_EXPORT Q_DECL_IMPORT
#endif

#endif // SHARE_CV_GUI_LIB_H
