#ifndef INSYDECOMMON_GLOBAL_H
#define INSYDECOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INSYDECOMMON_LIBRARY)
#  define INSYDECOMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INSYDECOMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INSYDECOMMON_GLOBAL_H
